In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [4]:
sent=['the glass of milk',
      'the cup of tea',
      'I am a good boy',
      'I am a good developer',
      'understanding the meaning of words',
      'your videos are good',]

In [5]:
voc_size=10000

In [6]:
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[8866, 8353, 4847, 9981],
 [8866, 6321, 4847, 8717],
 [9464, 4030, 9051, 7509, 376],
 [9464, 4030, 9051, 7509, 7837],
 [2700, 8866, 1239, 4847, 4125],
 [3375, 3730, 2759, 7509]]

In [8]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

In [10]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 8866 8353 4847 9981]
 [   0    0    0    0 8866 6321 4847 8717]
 [   0    0    0 9464 4030 9051 7509  376]
 [   0    0    0 9464 4030 9051 7509 7837]
 [   0    0    0 2700 8866 1239 4847 4125]
 [   0    0    0    0 3375 3730 2759 7509]]


In [11]:
dim =10


In [15]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [16]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)              │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [17]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 395ms/step


array([[[ 0.0137111 , -0.04985014, -0.01245616, -0.04843792,
          0.03277585,  0.00911633, -0.04752873, -0.0098277 ,
          0.03213215,  0.03645244],
        [ 0.0137111 , -0.04985014, -0.01245616, -0.04843792,
          0.03277585,  0.00911633, -0.04752873, -0.0098277 ,
          0.03213215,  0.03645244],
        [ 0.0137111 , -0.04985014, -0.01245616, -0.04843792,
          0.03277585,  0.00911633, -0.04752873, -0.0098277 ,
          0.03213215,  0.03645244],
        [ 0.0137111 , -0.04985014, -0.01245616, -0.04843792,
          0.03277585,  0.00911633, -0.04752873, -0.0098277 ,
          0.03213215,  0.03645244],
        [ 0.0343903 ,  0.02322705,  0.04104709, -0.04440302,
         -0.03558799, -0.00746635, -0.00781729, -0.04764522,
          0.03636858, -0.01888352],
        [ 0.00410395, -0.03842528,  0.03856726, -0.00915922,
          0.01186801,  0.02961684,  0.00745617, -0.0101946 ,
          0.01598073,  0.01409734],
        [-0.0053219 , -0.0219555 , -0.0458238 , -0.0

In [20]:
model.predict(embedded_docs[0])

ValueError: Exception encountered when calling Sequential.call().

Cannot take the length of shape with unknown rank.

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=<unknown>, dtype=int32)
  • training=False
  • mask=None

In [21]:
# Reshape the input to have 2 dimensions
import numpy as np
input_data = np.expand_dims(embedded_docs[0], axis=0)  # Add a batch dimension

# Now, make the prediction
predictions = model.predict(input_data)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step
